services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc
    restart: no
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${SERVICE_USER_MINIO} ${SERVICE_PASSWORD_MINIO};
      mc mb --ignore-existing local/${MINIO_BUCKET_NAME};
      tail -f /dev/null
      "

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    environment:
      SERVICE_FQDN_MAILPIT_8025:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 5s
      timeout: 5s
      retries: 5

  healthybase:
    image: kiraaziz/healthybase:latest
    restart: unless-stopped
    environment:
      SERVICE_FQDN_HEALTHYBASE_3000:
      APP_URL: ${SERVICE_URL_HEALTHYBASE_3000}
      NEXTAUTH_URL: ${SERVICE_URL_HEALTHYBASE_3000}
      AUTH_SECRET: ${SERVICE_BASE64_64_AUTHSECRET}
      JOB_KEY: ${SERVICE_PASSWORD_JOBKEY}
      ENTERPRISE_EMAIL: ${ENTERPRISE_EMAIL:-support@example.com}
      DATABASE_URL: postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-postgres}
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${SERVICE_USER_MINIO}
      MINIO_SECRET_KEY: ${SERVICE_PASSWORD_MINIO}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-database-backups}
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_SECURE: false
      SMTP_USER: ${SMTP_USER:-any}
      SMTP_PASS: ${SMTP_PASS:-any}
      EMAIL_FROM: ${EMAIL_FROM:-support@example.com}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  minio_data: